### ISSUE TITLE
Create SLA set up checklist

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/internal#16]
### Description
Need to set up a checklist of what needs to be done so everything is ready for SLA (e.g. where log ins are stored, sentry set up )

**Comment by yalla-coop-sla** [comment]
### When a new SLA or Warranty contract is signed:

**Project Lead Responsibilities**
- [ ] Works with Appoint Dev Lead and Technical Assistant roles for this project
- [ ] Add project to [SLA + Warranty Table in Notion](https://www.notion.so/yallacooperative/SLA-Warranty-d7667da4ea3b45f6a3544402099b606f), noting themselves, Dev Lead, and Technical Assistant
- [ ] Alert SLA Lead via Discord channel (#sla) that there is a new project under SLA or Warranty. Ensure to @ SLA Lead (documented at the top of [SLA + Warranty Table in Notion](https://www.notion.so/yallacooperative/SLA-Warranty-d7667da4ea3b45f6a3544402099b606f))
- [ ] Ensure that repository includes up-to-date issue templates. 
  - Bug issue should @ the SLA lead and the project lead
  - Ensure repo includes SLA / Warranty process documentation
- [ ] Introduce current SLA Lead to the client via email (copying in sla@yallacooperative.com)
- [ ] Ensures that client is told to always cc in sla@yallacooperative.com for email and that they are aware of the Github issue detailing the SLA / Warranty process

**Dev Lead Responsibilities**
- [ ] Sets up Sentry for the project
- [ ] Adds sla@yallacooperative.com email address to Sentry report notifications
- [ ] _Shares logins with rest of team(where??)_

**SLA Lead Responsibilities**
- [ ] Responds to client introduction email
- [ ] Books in the live walkthrough of SLA / Warranty processes with the client

**Technical Assistant Responsibilities**
- [ ] Prepares template for project's first SLA / Warranty report and ensures that it is linked in the [SLA + Warranty Table in Notion](https://www.notion.so/yallacooperative/SLA-Warranty-d7667da4ea3b45f6a3544402099b606f)

### In action with issues raised by the client:

**SLA Lead Responsibilities**
For issues raised in repository:
- [ ] Respond to client, letting them know that we have seen the issue and are looking into it
- [ ] Alert the Project Lead and Dev Lead on that project
- [ ] Work with Dev Lead to assign someone to work on that issue

For issues coming in via email:
- [ ] Respond to client, letting them know that we have seen the issue and are looking into it
- [ ] Prompt the client to use the bug issue template; if not possible, send them a Google form prompting them to provide the necessary bits of information
- [ ] Alert the Project Lead and Dev Lead on that project
- [ ] Work with Dev Lead to assign someone to work on that issue

**Dev Lead Responsibilities**
- [ ] After being notified by SLA Lead, assign someone to work on bug

**Assigned Dev Responsibilities**
- [ ] After being assigned by Dev Lead, conduct an initial investigation (1-2 hours)
- [ ] Provide a written update on Github issue @ing the SLA Lead and the client including:
- Whether it is an SLA or Warranty issue
- Next actions
- Estimated time to resolve (if possible)
- When an update will next be provided 

### On the resolution of issues:

**SLA Lead Responsibilities**
- [ ]  Gives the issue a 'fixed' tag and provides a final update (if required) in the issue
- [ ]  Asks client to confirm they are happy and if so then close the issue
- [ ]  Review time spent against that month and warn client if they are within 30% of their allocated time left (e.g. if someone has 3 days a month this is if they only have 1 day left)

### General maintanence:

**Comment by cyberteenie** [comment]
Please see Notion for most up to date checklist: 
https://www.notion.so/yallacooperative/SLA-Internal-Process-Checklist-a98059677bed4a50a8e8ffc84b811047
